---
title: "Week 4 weekend hw"
author: "Peter Menzies"
date: "15/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
```

# Q1.1

```{r, message=FALSE}
here()
salaries <- read_csv(here("data/data/salaries.csv"))
```

```{r}
salaries %>% 
  select(beginning_salary, current_salary)
```

# 1.2

```{r}
salaries %>% 
  filter(age > 50, current_salary > 20000)
```

# 1.3

```{r}
salaries %>% 
  arrange(desc(current_salary))
```

# 1.4
```{r}
salaries %>% 
  mutate(beginning_salary_pence = beginning_salary * 100,
         current_salary_pence = current_salary * 100)
```

# 1.5

```{r}
salaries %>% 
  arrange(desc(age)) %>% 
  summarise(max_age = head(age, 1),
            min_age = tail(age, 1))


# could have just used max() and min() then arrange isnt required
            
```


# 1.6 

```{r}
salaries %>% 
  arrange(desc(current_salary)) %>% 
  summarise(max_salary = head(current_salary, 1),
            min_salary = tail(current_salary, 1))
```

# 1.7

```{r}
salaries %>% 
  filter(age < 30)
```

# 1.8 

```{r}
salaries %>% 
  arrange(educational_level, age)
```

# 1.9

```{r}
salaries %>% 
  select(where(is.numeric))

salaries %>% 
  select_if(is.numeric)
```

# 1.10

* should have used OR 

```{r}
salaries %>% 
  filter(work_experience <2 | educational_level < 12)
```

# 1.11

```{r}
salaries %>% 
  mutate(beginning_salary_1000s = beginning_salary / 1000,
         current_salary_1000s = current_salary / 1000)
```

# 1.12

```{r}
salaries %>% 
  filter(gender == "femaale", employment_category == "security officer")
```

# 1.13

```{r, message=FALSE}
salaries %>% 
  group_by(employment_category) %>% 
  summarise(avg_salary = mean(current_salary))
```

# 1.14

```{r, message=F}
salaries %>% 
  filter(gender == "male") %>% 
  group_by(employment_category) %>% 
  summarise(avg_male_salary = mean(current_salary))

```

# 1.15

```{r, message=F}
salaries %>% 
  group_by(gender, is_white) %>% 
  summarise(number_employess = n())
```

# 1.16

```{r}
mutate(salaries, mean_age = mean(current_salary))
```

```{r}
salaries %>% 
  group_by() %>% 
  mutate(mean_salary = mean(current_salary))
```

* Mutate ignores the the group_by?

# Q2
# 2.1

```{r, message=F}
salaries %>% 
  filter(educational_level <= 16) %>% 
  group_by(educational_level) %>% 
  summarise(mean_salary = mean(current_salary)) %>% 
  arrange(desc(mean_salary))
```

# 2.2

```{r, message=F}
salaries %>% 
  filter(work_experience < 2) %>% 
  group_by(gender, employment_category) %>% 
  summarise(mean_salary = mean(current_salary))
```

# 2.3

```{r, message=F}
salaries %>% 
  group_by(employment_category) %>% 
  summarise(mean_salary = mean(current_salary),
            median_salary = median(current_salary),
            difference = mean_salary - median_salary) %>% 
  arrange(desc(abs(difference)))
```

# Q3

```{r}
beers <- read.delim("~/codeclan_homework_PeterM/week_04/weekend/data/data/beer.txt", sep = ";")
```

# 3.1
```{r}
beers %>% 
  filter(is.na(carbohydrates))
```
# 3.2

```{r}
beers %>% 
  filter(is.na(brand))
```


# 3.3

• The rows missing brand are also missing loads of other variables.

• I'd drop brand NA's but ignore carbohydrate NA's

# Q4

* My R seems to think it is in the "markdown" folder when I try to read in a file. Using here() made no difference

```{r}
here()
inmates <- read_tsv("~/codeclan_homework_PeterM/week_04/weekend/data/data/inmates.tsv")
```

# 4.1

```{r}
inmates %>% 
  mutate(gender = recode(gender, 
                         "M" = "Male",
                         "F" = "Female")) %>% 
  distinct(gender)
```

# 4.2

```{r}
inmates %>% 
  mutate(race = recode(race, 
                       "AMER" = "Other",
                       "IND" = "Other", 
                       "ASIAN" = "Other",),
         race = str_to_title(race))
```

# 4.3
* a
```{r}
inmates_bond_level <- inmates %>% 
  mutate(bond_level = case_when(
    bond_amount > 1000000 ~ "High",
    T ~ "Normal"))
inmates_bond_level
```

• b
```{r, message=F}
inmates_bond_level %>% 
  group_by(bond_level) %>% 
  summarise(number_inmates = n())
```

# 4.4

```{r}
inmates %>% 
  select(identifier, detainer) %>% 
  mutate(detainer = case_when(
    !detainer %in% c("NONE", "IMMIGRATION", "FEDERAL") ~ "Other",
    T ~ str_to_title(detainer)))



```




















